-- Phase 2.5 follow-up: split the org_isolation policy into a read/update gate
-- (USING) and a permissive insert gate (WITH CHECK true).
--
-- Why this is needed:
--   When `CREATE POLICY ... USING (expr)` is created without an explicit
--   WITH CHECK clause, Postgres applies the USING expression to INSERT (and
--   the UPDATE write-side) by default. For org-scoped tables, this means an
--   INSERT fails unless app.org_id is already set to the new row's
--   organizationId. That works for ordinary writes inside db().$transaction()
--   (which SET LOCAL app.org_id), but it cannot work for the very first
--   INSERT into Organization during self-serve provisioning — the new org's
--   id is generated by that insert.
--
-- Why permissive WITH CHECK is safe here:
--   Tenancy on writes is enforced at the application layer: the db() wrapper
--   in lib/db/tenant.ts injects organizationId on every CREATE, and the
--   services/routes pass explicit organizationId where the wrapper does not
--   apply. RLS USING remains the defense-in-depth backstop on READ paths
--   (SELECT/UPDATE/DELETE), which is where cross-tenant leakage would
--   actually surface.
--
-- This migration:
--   1. Drops the existing org_isolation policy on each affected table.
--   2. Recreates it with USING (existing org-id match) AND WITH CHECK (true).
--
-- Idempotent: DROP POLICY IF EXISTS + CREATE POLICY (which errors if the
-- name already exists — we drop first to be safe under re-runs).

DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'Brother','Role','Semester','Deadline','InstagramTask','Doc',
    'PartyEvent','CalendarEvent','ServiceEvent','ActivityLog',
    'Transaction','Budget','ChapterAnnouncement','Membership',
    'OperationalEvent'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS org_isolation ON %I', tbl);
    EXECUTE format(
      'CREATE POLICY org_isolation ON %I
         USING ("organizationId" = NULLIF(current_setting(''app.org_id'', true), '''')::integer)
         WITH CHECK (true)',
      tbl
    );
  END LOOP;
END $$;

-- Organization is keyed by id, not organizationId.
DROP POLICY IF EXISTS org_isolation ON "Organization";
CREATE POLICY org_isolation ON "Organization"
  USING ("id" = NULLIF(current_setting('app.org_id', true), '')::integer)
  WITH CHECK (true);

-- OrganizationConfig was added after Phase 2.5; never had a policy. We add
-- the same shape now: scope reads to current org, allow writes (app enforces
-- via the unique organizationId constraint + Prisma layer).
ALTER TABLE "OrganizationConfig" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON "OrganizationConfig";
CREATE POLICY org_isolation ON "OrganizationConfig"
  USING ("organizationId" = NULLIF(current_setting('app.org_id', true), '')::integer)
  WITH CHECK (true);
