'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='chaptos-warm-app-v1';let DB;try{DB=JSON.parse(localStorage.getItem(KEY))||structuredClone(SEED)}catch{DB=structuredClone(SEED)}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TODAY='2026-09-10', cats={chapter:['Chapter','sky'],social:['Social','butter'],fundy:['Fundraiser','mint'],program:['Program','lilac'],party:['Party','rose'],deadline:['Deadline','peach'],service:['Service','mint']};
const routes={dashboard:['Dashboard','Overview'],timeline:['Timeline','Overview'],brothers:['Brotherhood','Members'],chapter:['Chapter','Members'],tasks:['Tasks','Members'],docs:['Docs','Operations'],instagram:['Instagram','Operations'],events:['Programming','Operations'],service:['Service','Operations'],parties:['Parties','Operations'],treasury:['Treasury','Operations'],settings:['Settings','System'],billing:['Billing','System']};
const U={filter:'All',query:'',tab:'',sort:'name',sortDir:1,month:8,year:2026,collapsed:new Set(['2026-08']),meeting:6,setting:'index',showDone:false,selected:null,chart:'ALL'};
let route='dashboard',drawerState=null,formHandler=null,afterForm=null,askHistory=[],proposal=null;
const date=d=>new Date(d+'T12:00:00');const fmt=d=>d?date(d).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'Date to be set';const dow=d=>date(d).toLocaleDateString('en-US',{weekday:'short'});const money=n=>Number(n).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number.isInteger(Number(n))?0:2});
const sum=(a,key)=>a.reduce((n,x)=>n+Number(x[key]||0),0),average=(a,key)=>a.length?sum(a,key)/a.length:0;
const rel=d=>{if(!d)return'Unscheduled';const n=Math.round((date(d)-date(TODAY))/86400000);return n===0?'Today':n===1?'Tomorrow':n===-1?'Yesterday':n>0?`In ${n} days`:`${-n} days ago`};
const tint=t=>`--t-ink:var(--${t}-ink);--t-soft:var(--${t}-soft);--t-border:var(--${t}-bd);--t-base:var(--${t})`;
const icon=(name='Timeline')=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${NAV_ICONS[name]||({search:'M21 21l-5-5M18 10a8 8 0 11-16 0 8 8 0 0116 0',chevron:'M9 5l7 7-7 7',check:'M5 12l4 4L19 6',spark:'M12 3l2.2 6.8L21 12l-6.8 2.2L12 21l-2.2-6.8L3 12l6.8-2.2Z',folder:'M3 7h7l2-3h8v16H3Z',clock:'M12 6v6l4 2M21 12a9 9 0 11-18 0 9 9 0 0118 0',flag:'M5 21V3m0 1h14l-3 4 3 4H5'}[name]||NAV_ICONS.Dashboard)}"/></svg>`;
const btn=(label,action='',id='',cls='',extra='')=>`<button type="button" class="btn ${cls}" ${action?`data-action="${action}"`:''} ${id!==''?`data-id="${esc(id)}"`:''} ${extra}>${label}</button>`;
const link=(label,to,cls='btn ghost')=>`<a class="${cls}" href="#/${to}">${label}</a>`;
const pill=(text,t='lilac')=>`<span class="pill" style="${tint(t)}">${esc(text)}</span>`;
const avatar=(m,large=false)=>`<span class="avatar ${large?'large':''}" style="${tint(['lilac','mint','sky','peach','rose','butter'][(m.id||1)%6])}">${esc(m.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span>`;
const card=(title,body,t='sky',ic='Timeline',actions='')=>`<section class="card" style="${tint(t)}"><div class="card-head"><span class="icon-tile">${icon(ic)}</span><h2>${title}</h2><span class="end">${actions}</span></div>${body}</section>`;
const header=(kicker,title,lede,actions='',ai=false)=>`<section class="heading"><div class="heading-copy"><p class="kicker"><span class="today">${esc(kicker)}</span><span>${esc(DB.org.term)}</span></p><h1>${title}</h1><p class="lede">${ai?'<span class="ai">AI</span>':''}${lede}</p></div><div class="actions">${actions}</div></section>`;
const metric=(label,value,note,t='sky',ic='Timeline',action='',id='')=>`<${action?'button':'div'} class="metric" style="${tint(t)}" ${action?`data-action="${action}" data-id="${id}"`:''}><div class="metric-label">${icon(ic)}${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></${action?'button':'div'}>`;
const metrics=items=>`<section class="metrics ${items.length>4?'six':''}" aria-label="At a glance">${items.join('')}</section>`;
const tabs=(values,active,kind='tab')=>`<div class="tabs" aria-label="${kind==='filter'?'Filter':'View'}">${values.map(v=>{const [id,label,count]=Array.isArray(v)?v:[v,v];return `<button class="tab ${active===id?'on':''}" data-action="${kind}" data-id="${esc(id)}" aria-pressed="${active===id}">${label}${count!==undefined?`<b>${count}</b>`:''}</button>`}).join('')}</div>`;
const search=placeholder=>`<div class="search">${icon('search')}<input id="search" aria-label="${esc(placeholder)}" placeholder="${esc(placeholder)}" value="${esc(U.query)}"></div>`;
const empty=(title='Nothing here yet',copy='Add the first item to get started.',action='')=>`<div class="empty">${icon('Timeline')}<h3>${title}</h3><p>${copy}</p>${action}</div>`;
const section=(title,count='')=>`<div class="section-label"><h2>${title}</h2>${count?`<span class="small">${count}</span>`:''}</div>`;
const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}">No matching records.</td></tr>`}</tbody></table></div>`;
const memberName=id=>DB.members.find(m=>m.id===id)?.name||'Member';
const liveMembers=()=>DB.members.filter(m=>!m.archived);
function memberStatus(m){const t=DB.settings.thresholds;return m.attendance<t.attendance-10||m.gpa<t.gpa?'At Risk':m.attendance<t.attendance||m.hours<t.service?'Watch':'Good'}
const statusTone=s=>s==='Good'||s==='done'||s==='posted'||s==='approved'?'mint':s==='At Risk'||s==='overdue'||s==='rejected'?'peach':'butter';
const balance=()=>DB.transactions.filter(t=>t.status==='posted').reduce((n,t)=>n+(t.type==='income'?t.amount:-t.amount),0);
const overdueTasks=()=>DB.tasks.filter(t=>t.status!=='done'&&t.date<TODAY);
const upcoming=()=>DB.events.filter(e=>e.date>=TODAY).sort((a,b)=>a.date.localeCompare(b.date));
function save(message,tone='mint'){try{localStorage.setItem(KEY,JSON.stringify(DB))}catch{}if(message){DB.activity.unshift({text:message,date:'Sep 10 · Just now',tone});try{localStorage.setItem(KEY,JSON.stringify(DB))}catch{}toast(message)}render()}
let toastTimer;function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200)}
function navName(key){if(key==='brothers')return DB.settings.vocabulary.Member==='Brother'?'Brotherhood':DB.settings.vocabulary.Member+'s';if(key==='chapter')return DB.settings.vocabulary.Meetings;if(key==='treasury')return DB.settings.vocabulary.Treasury;return routes[key]?.[0]||key}
function sidebar(){let out=`<button class="org" data-action="org"><span class="org__mk">${esc(DB.org.initials)}</span><span class="org__n"><b>${esc(DB.org.name)}</b><span>${esc(DB.org.term)}</span></span><span class="org__c">⌃</span></button>`;for(const group of ['Overview','Members','Operations']){out+=`<p class="nav-h">${group}</p><nav class="nav">`;for(const [key,[label,g]]of Object.entries(routes)){if(g!==group||DB.settings.workflows[key]===false)continue;const count=key==='brothers'?DB.joins.length:key==='timeline'?DB.excuses.length:key==='treasury'?DB.reimbursements.filter(r=>r.status==='pending').length:0;out+=`<a href="#/${key}" class="${route===key?'on':''}" ${route===key?'aria-current="page"':''}>${icon(label)}${esc(navName(key))}${count?`<span class="badge">${count}</span>`:''}</a>`}out+='</nav>'}out+=`<div class="side__foot"><nav class="nav"><a href="#/settings" class="${route==='settings'?'on':''}">${icon('Settings')}Settings</a><a href="#/billing" class="${route==='billing'?'on':''}">${icon('Treasury')}Billing</a></nav><button class="me" data-action="profile"><span class="me__av">MR</span><span class="me__n"><b>Marcus Reyes</b><span>President · Org admin</span></span></button></div>`;$('#sidebar').innerHTML=out;$('#sidebar').inert=innerWidth<1024&&!$('#sidebar').classList.contains('open')}
function render(){sidebar();$('#mobile-title').textContent=navName(route);$('#foot-org').textContent=DB.org.name+' · '+DB.org.term;document.title=`${navName(route)} · ChaptOS Warm Mock`;$('#page').innerHTML=({dashboard:dashboardPage,timeline:timelinePage,brothers:brothersPage,chapter:chapterPage,tasks:tasksPage,docs:docsPage,instagram:instagramPage,events:eventsPage,service:servicePage,parties:partiesPage,treasury:treasuryPage,settings:settingsPage,billing:billingPage}[route]||dashboardPage)();}
function navigate(){const parts=(location.hash||'#/dashboard').replace(/^#\/?/,'').split('/');route=routes[parts[0]]?parts[0]:'dashboard';U.query='';U.filter='All';U.tab='';U.setting=parts[1]||'index';U.selected=null;$('#sidebar').classList.remove('open');$('#nav-shade').hidden=true;for(const d of $$('dialog[open]'))d.close();render();window.scrollTo(0,0)}
function modal(title,body,handler=null){$('#modal-title').textContent=title;$('#modal-kicker').textContent=DB.org.name;$('#modal-body').innerHTML=body;formHandler=handler;if(!$('#modal').open)$('#modal').showModal()}
function openForm(title,fields,handler,submit='Save changes',note='Changes are saved only in this local mock.'){modal(title,`<form class="form" id="generic-form">${fields}<p class="field-help">${note}</p><div class="form-foot">${btn('Cancel','close-modal','','ghost')}<button class="btn primary" type="submit">${submit}</button></div></form>`,handler)}
function field(label,name,value='',type='text',required=false,options=null){return `<label>${esc(label)}${options?`<select name="${name}">${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`}).join('')}</select>`:type==='textarea'?`<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'step="any" min="0"':''}>`}</label>`}
const checkField=(label,name,value=false)=>`<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${esc(label)}</label>`;
function confirmAction(title,copy,fn){modal(title,`<div class="modal-content"><p class="detail-lines">${esc(copy)}</p><div class="actions" style="margin-top:22px">${btn('Cancel','close-modal','','ghost')}${btn('Confirm','confirm','','danger')}</div></div>`);afterForm=fn}
function draw(title,body,t='lilac',actions=''){ $('#drawer-body').innerHTML=`<div class="drawer-top">${btn('← Back','close-drawer','','small ghost')}<div class="actions">${actions}<button class="icon-btn" data-action="close-drawer" aria-label="Close details">×</button></div></div><div class="drawer-content" style="${tint(t)}"><h2 id="drawer-title" class="eyebrow">${esc(title)}</h2>${body}</div>`;if(!$('#drawer').open)$('#drawer').showModal()}
function csv(name,heads,rows){const quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const blob=new Blob([[heads,...rows].map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Exported '+name+'.csv')}
function calendarGrid(items,kind='event'){const y=U.year,m=U.month,first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();return `<div class="calendar-wrap"><div class="calendar">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="cal-head">${d}</div>`).join('')}${Array.from({length:first},()=>'<div class="cal-day"></div>').join('')}${Array.from({length:days},(_,i)=>{const d=`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return `<div class="cal-day ${d===TODAY?'today':''}"><span>${i+1}</span>${items.filter(e=>e.date===d).map(e=>`<button class="cal-item" style="${tint(cats[e.category]?.[1]||'butter')}" data-action="${kind}" data-id="${e.id}">${esc(e.title)}</button>`).join('')}</div>`}).join('')}</div></div>`}
function chart(){const list=DB.transactions.filter(t=>t.status==='posted').sort((a,b)=>a.date.localeCompare(b.date));let b=0;const vals=list.map(t=>b+=t.type==='income'?t.amount:-t.amount);const max=Math.max(...vals,1),min=Math.min(...vals,0),points=vals.map((v,i)=>`${i*600/Math.max(vals.length-1,1)},${140-(v-min)/(max-min||1)*120}`);return `<svg class="chart" viewBox="0 0 600 155" preserveAspectRatio="none" role="img" aria-label="Running balance from posted transactions"><path d="M0 30H600M0 85H600M0 140H600" stroke="var(--line)" fill="none"/><path d="M${points.join(' L')} L600 155 L0 155 Z" fill="var(--mint-ink)" opacity=".08"/><path d="M${points.join(' L')}" fill="none" stroke="var(--mint-ink)" stroke-width="2.5" stroke-linejoin="round"/></svg><div class="chart-labels"><span>AUG 24</span><span>AUG 29</span><span>SEP 05</span><span>TODAY</span></div>`}
