function programmingForm(kind){
  const idea=kind==='idea';
  const categories=Object.entries(cats).filter(([key])=>!['deadline',...(idea?['chapter','party']:[])].includes(key));
  const body=`<form id="generic-form" class="form programme-form">
    <div class="capture-intro" style="${tint(idea?'butter':'lilac')}"><span class="capture-icon">${icon(idea?'spark':'Timeline')}</span><p>${idea?'A good programme starts with a small idea.':'Give the chapter something to look forward to.'}<small>${idea?'Start with a name. The details can come later.':'Set the essentials now. Keep refining as plans take shape.'}</small></p></div>
    <section class="programme-section"><label class="programme-title">${idea?'What’s the idea?':'Event name'} <input name="title" required maxlength="120" autofocus placeholder="${idea?'e.g. Alumni coffee & career conversations':'e.g. Fall brotherhood dinner'}"></label>
    <label>${idea?'The spark':'About this event'} <span class="optional">Optional</span><textarea name="description" rows="3" placeholder="${idea?'What could this look like? Why would the chapter love it?':'What’s planned, and what should members know?'}"></textarea></label>
    <fieldset class="category-picker"><legend>Category</legend><div>${categories.map(([key,[label,tone]])=>`<label style="${tint(tone)}"><input type="radio" name="category" value="${key}" ${key==='program'?'checked':''}><span>${label}</span></label>`).join('')}</div></fieldset></section>
    ${idea?`<details class="programme-extra"><summary>Add a little direction <span>Owner, tentative date & budget</span></summary><div class="form-grid">${field('Owner','owner','Marcus Reyes','text',false,[['','Unassigned'],...liveMembers().map(m=>m.name)])}${field('Tentative date','date','','date')}${field('Estimated budget ($)','budget','','number')}</div></details><input type="hidden" name="stage" value="idea">`:`<section class="programme-section"><div class="programme-section-head">${icon('clock')}<h3>When & where</h3><span>Required date · optional time & place</span></div><div class="form-grid">${field('Date','date',TODAY,'date',true)}<label>Start time<input name="time" type="time"></label></div><label>Location <span class="optional">Optional while planning</span><input name="location" placeholder="Venue, room, or meeting link"></label></section>
    <section class="programme-section"><div class="programme-section-head">${icon('Brotherhood')}<h3>Make it happen</h3></div><div class="form-grid">${field('Owner','owner','Marcus Reyes','text',false,liveMembers().map(m=>m.name))}${field('Budget ($)','budget','','number')}</div><label class="attendance-option"><input type="checkbox" name="required"><span>Attendance required<small>Members are expected to attend this event.</small></span></label><fieldset class="stage-picker"><legend>How ready is it?</legend><label><input type="radio" name="stage" value="planning" checked><span>Still planning<small>Details are taking shape</small></span></label><label><input type="radio" name="stage" value="confirmed"><span>Confirmed<small>Date, place & owner are set</small></span></label></fieldset></section>`}
    <p id="programme-error" class="programme-error" role="alert" hidden></p>
    <div class="form-foot"><span class="save-hint">${idea?'Saved to Ideas':'Added to your programme'}</span>${btn('Cancel','close-modal','','ghost')}<button class="btn primary" type="submit">${idea?'Capture idea':'Add event'} ${icon('check')}</button></div>
  </form>`;
  modal(idea?'Capture an idea':'Add an event',body,f=>{
    const data=Object.fromEntries(f);data.title=data.title.trim();data.location=(data.location||'').trim();
    const error=$('#programme-error');
    if(!data.title){error.textContent='Give it a name before saving.';error.hidden=false;$('#generic-form [name=title]').focus();return false}
    if(data.stage==='confirmed'&&(!data.date||!data.location||!data.owner)){error.textContent='To confirm this event, add a date, location and owner.';error.hidden=false;$('#generic-form [name=location]').focus();return false}
    if(data.time){const [h,m]=data.time.split(':').map(Number);data.time=`${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
    DB.events.push({id:nextId(DB.events),status:'open',prep:[],hours:{},present:[],notes:'',revenue:0,cost:0,guests:0,date:'',time:'',location:'',...data,budget:Number(data.budget||0),required:f.has('required')});
    save(idea?'Idea captured — ready to explore.':`${data.title} added to the programme`);
  });
}
const nextId=a=>Math.max(0,...a.map(x=>x.id))+1;
function editRecord(kind,id){if(!id&&['idea','event'].includes(kind))return programmingForm(kind);const collections={event:'events',meeting:'events',service:'events',party:'events',idea:'events',task:'tasks',post:'posts',doc:'docs',transaction:'transactions',reimbursement:'reimbursements',poll:'polls'};const key=collections[kind];if(!key)return;const old=DB[key].find(x=>x.id===Number(id));const r=old||{};let fields=field('Title','title',r.title||'','text',true);
if(!['doc','reimbursement','poll'].includes(kind))fields+=field(kind==='task'?'Due date':'Date','date',r.date||TODAY,'date',kind!=='idea');
if(['event','meeting','service','party','idea'].includes(kind))fields+=field('Type','category',r.category||({meeting:'chapter',service:'service',party:'party'}[kind]||'program'),'text',false,Object.entries(cats).filter(([k])=>k!=='deadline').map(([k,v])=>[k,v[0]]))+field('Stage','stage',r.stage||(kind==='idea'?'idea':'planning'),'text',false,['idea','planning','confirmed','done'])+field('Time','time',r.time||'7:00 PM')+field('Location','location',r.location||'')+field('Budget','budget',r.budget||0,'number')+checkField('Attendance required','required',r.required);
if(['task','post','event','meeting','service','party','idea','doc'].includes(kind))fields+=field('Owner','owner',r.owner||'Marcus Reyes','text',false,liveMembers().map(m=>m.name));
if(kind==='post')fields+=field('Format','type',r.type||'Post','text',false,['Post','Story','Reel'])+field('Status','status',r.status||'planned','text',false,['planned','posted'])+field('Caption','caption',r.caption||'','textarea')+field('Linked event','eventId',r.eventId||'','text',false,[['','No linked event'],...DB.events.map(e=>[e.id,e.title])]);
if(kind==='doc')fields+=field('Folder','folder',r.folder||DB.folders[0],'text',false,DB.folders)+field('Kind','kind',r.kind||'Doc','text',false,['Doc','Sheet','Form','Link'])+field('URL','url',r.url||'https://example.com','url',true)+checkField('Pin document','pinned',r.pinned);
if(['transaction','reimbursement'].includes(kind))fields+=field('Amount','amount',r.amount||'','number',true)+field('Category','category',r.category||'Operations')+(kind==='transaction'?field('Type','type',r.type||'expense','text',false,['income','expense'])+field('Status','status',r.status||'posted','text',false,['posted','scheduled'])+field('Method','method',r.method||'Bank transfer'):field('Member','owner',r.owner||'Marcus Reyes','text',false,liveMembers().map(m=>m.name)));
if(kind==='poll')fields+=field('Closes','date',r.date||'2026-09-17','date',true)+field('Options (one per line)','options',(r.options||[{label:'Option one'},{label:'Option two'}]).map(o=>o.label).join('\n'),'textarea',true);
if(!['post','poll','transaction','reimbursement'].includes(kind))fields+=field('Description','description',r.description||'','textarea');
openForm((old?'Edit ':'New ')+kind,fields,f=>{const data=Object.fromEntries(f);for(const n of ['amount','budget','eventId'])if(n in data)data[n]=Number(data[n]);if(['event','meeting','service','party','idea'].includes(kind)){data.required=f.has('required');if(data.stage==='confirmed'&&(!data.date||!data.location||!data.owner)){toast('Add a date, location and owner before confirming.');return false}}if(kind==='reimbursement'){data.name=data.owner;data.date=TODAY}if(kind==='doc')data.date=r.date||TODAY;if(kind==='doc')data.pinned=f.has('pinned');if(kind==='poll'){const options=data.options.split('\n').map(s=>s.trim()).filter(Boolean);if(options.length<2){toast('A poll needs at least two options.');return false}data.options=options.map(label=>({label,votes:0}));data.voted=null;data.closed=false}if(old)Object.assign(old,data);else DB[key].push({id:nextId(DB[key]),status:kind==='reimbursement'?'pending':'open',prep:[],hours:{},present:[],notes:'',revenue:0,cost:0,guests:0,...data});save(`${data.title} ${old?'updated':'created'}`);});}
function detail(kind,id){const key={member:'members',event:'events',task:'tasks',post:'posts',doc:'docs',transaction:'transactions'}[kind];const r=DB[key]?.find(x=>x.id===Number(id));if(!r)return;drawerState={kind,id};let body='',actions='';if(kind==='member'){body=`${avatar(r,true)}<h1>${esc(r.name)}</h1>${pill(r.role,'lilac')} ${pill(memberStatus(r),statusTone(memberStatus(r)))}<p>${esc(r.email)}</p>${metrics([metric('Attendance',r.attendance+'%','This semester'),metric('Service',r.hours+'h','Logged hours','mint'),metric('GPA',r.gpa,'Current GPA','lilac'),metric('Dues',money(r.dues),'Outstanding','butter')])}<div class="actions">${btn('Edit member','edit-member',r.id)}${btn('Record payment','dues',r.id)}</div>`;}else{body=`<h1>${esc(r.title)}</h1><p class="lede">${esc(r.description||r.caption||'')}</p><div class="row"><span>${fmt(r.date)}</span>${pill(r.stage||r.status||r.kind,cats[r.category]?.[1]||'lilac')}</div>`;if(r.owner)body+=`<div class="row"><span>Owner</span><b>${esc(r.owner)}</b></div>`;if(kind==='event'){body+=`<div class="row"><span>Location</span><b>${esc(r.location||'To be decided')}</b></div><div class="row"><span>Time</span><b>${esc(r.time)}</b></div><div class="row"><span>Budget</span><b>${money(r.budget)}</b></div><h3>Preparation</h3>${(r.prep||[]).map((p,i)=>`<label class="row"><span>${esc(p.label||p.text||p)}</span><input type="checkbox" data-prep="${r.id}:${i}" ${p.done?'checked':''}></label>`).join('')||'<p class="muted">No checklist items yet.</p>'}${btn('Add checklist item','prep-add',r.id)}<div class="actions" style="margin-top:24px">${r.category==='chapter'?btn('Take attendance','roll',r.id):''}${r.category==='service'?btn('Log hours','service-hours',r.id):''}${r.category==='party'?btn('Wrap up','wrap',r.id):''}</div>`}if(kind==='task')body+=btn(r.status==='done'?'Reopen task':'Mark complete','task-toggle',r.id,'primary');if(kind==='post')body+=btn(r.status==='posted'?'Move to planned':'Mark posted','post-toggle',r.id,'primary');if(kind==='doc')body+=`<p>${esc(r.folder)} · ${esc(r.kind)}</p><a class="btn primary" href="${/^https?:/.test(r.url)?esc(r.url):'#'}" target="_blank" rel="noopener">Open document ↗</a>`;if(kind==='transaction')body+=`<h2>${money(r.amount)}</h2><p>${esc(r.category)} · ${esc(r.method)}</p>`;actions=btn('Edit','edit-'+kind,r.id,'small')}draw(kind==='member'?'Member profile':kind,body,cats[r.category]?.[1]||'lilac',actions)}
function ask(q){if(!$('#ask-dialog').open)$('#ask-dialog').showModal();if(q){let text,links;if(/dues|owe|money|balance/i.test(q)){text=`The chapter has ${money(balance())} on hand. ${DB.members.filter(m=>m.dues>0).length} members have outstanding dues, totaling ${money(sum(DB.members,'dues'))}.`;links=link('Review dues','treasury')}else if(/risk|standing|attendance/i.test(q)){const ms=liveMembers().filter(m=>memberStatus(m)==='At Risk');text=`${ms.map(m=>m.name).join(' and ')} need a check-in based on the current standing thresholds. Review their attendance and academic record before deciding next steps.`;links=link('Review members','brothers')}else{text=`There are ${overdueTasks().length} overdue tasks. Coming up: ${upcoming().slice(0,3).map(e=>e.title+' ('+fmt(e.date)+')').join(', ')}.`;links=link('Open timeline','timeline')}askHistory.push(`<div class="ask-question">${esc(q)}</div><div class="ask-answer"><span class="eyebrow">FROM YOUR SAMPLE RECORDS</span><p>${text}</p>${links}${btn('Draft a follow-up task','ask-propose','','small')}</div>`)}$('#ask-body').innerHTML=askHistory.join('')||`<div class="ask-answer"><p>A little clarity for your chapter.</p><div class="suggestions">${['Who still owes dues?','Who needs a check-in?','What’s coming up?'].map(q=>btn(q,'ask-question',q)).join('')}</div></div>`;$('#ask-body').scrollTop=$('#ask-body').scrollHeight}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-open]');if(!el)return;const a=el.dataset.action||el.dataset.open,id=el.dataset.id,n=Number(id);if(['member','event','task','post','doc','transaction'].includes(a))return detail(a,id);if(a?.startsWith('edit-')&&['event','task','post','doc','transaction','poll'].includes(a.slice(5)))return editRecord(a.slice(5),id);
if(a==='new'&&id!=='folder')return editRecord(id||'event');if(a==='tab'||a==='filter'){U[a]=id;render()}else if(a==='sort'){U.sortDir=U.sort===id?-U.sortDir:1;U.sort=id;render()}else if(a==='menu'){$('#sidebar').classList.toggle('open');$('#sidebar').inert=false;$('#nav-shade').hidden=false}else if(a==='close-modal')$('#modal').close();else if(a==='close-drawer')$('#drawer').close();else if(a==='close-ask')$('#ask-dialog').close();else if(a==='confirm'){afterForm?.();$('#modal').close()}else if(a==='reset')confirmAction('Reset sample data?','All edits in this mock will be replaced with the original fictional records.',()=>{DB=structuredClone(SEED);save('Sample data reset')});
else if(a==='month-collapse'){U.collapsed.has(id)?U.collapsed.delete(id):U.collapsed.add(id);render()}else if(a==='calendar-prev'||a==='calendar-next'){U.month+=a==='calendar-prev'?-1:1;if(U.month<0){U.month=11;U.year--}if(U.month>11){U.month=0;U.year++}render()}else if(a==='today'){U.month=8;U.year=2026;U.collapsed.delete('2026-09');render();$('.today-line')?.scrollIntoView({block:'center',behavior:'smooth'})}else if(a==='meeting'){U.meeting=n;render()}else if(a==='task-toggle'){const t=DB.tasks.find(x=>x.id===n);t.status=t.status==='done'?'open':'done';save('Task '+(t.status==='done'?'completed':'reopened'));if($('#drawer').open)detail('task',n)}else if(a==='post-toggle'){const p=DB.posts.find(x=>x.id===n);p.status=p.status==='posted'?'planned':'posted';save('Post status updated');detail('post',n)}else if(a==='doc-pin'){const d=DB.docs.find(x=>x.id===n);d.pinned=!d.pinned;save(d.pinned?'Document pinned':'Document unpinned')}
else if(a==='join-approve'||a==='join-reject'){const j=DB.joins.find(x=>x.id===n);if(a==='join-approve')DB.members.push({id:nextId(DB.members),name:j.name,email:j.email,role:'Member',dues:0,gpa:0,attendance:100,hours:0});DB.joins=DB.joins.filter(x=>x.id!==n);save(j.name+(a==='join-approve'?' approved':' declined'))}else if(a==='excuse-approve'||a==='excuse-reject'){DB.excuses=DB.excuses.filter(x=>x.id!==n);save('Excuse '+(a==='excuse-approve'?'approved':'declined'))}else if(a==='vote'){const [p,i]=id.split(':').map(Number),poll=DB.polls.find(x=>x.id===p);if(!poll.closed&&poll.voted===null){poll.options[i].votes++;poll.voted=i;save('Vote recorded')}}else if(a==='poll-close'){DB.polls.find(x=>x.id===n).closed=true;save('Poll closed')}
else if(a==='invite'){openForm('Create invitation',field('Label','title','Fall recruitment','text',true)+field('Role','role','Member','text',false,DB.roles.map(r=>r.name||r.label)),f=>{DB.invitations.push({id:nextId(DB.invitations),...Object.fromEntries(f),uses:0,active:true});save('Invite created');return true},'Create local invite','This previews the reviewed join flow. No live invitation is sent.')}else if(a==='invite-toggle'){const i=DB.invitations.find(x=>x.id===n);i.active=!i.active;save('Invitation updated')}
else if(a==='dues'||a==='assign-dues'){const m=DB.members.find(x=>x.id===n);openForm(a==='dues'?'Record dues payment':'Assign dues',`<h3>${esc(m.name)}</h3>`+field('Amount','amount',a==='dues'?m.dues:120,'number',true),f=>{const amount=Number(f.get('amount'));if(a==='dues'&&amount>m.dues){toast('Payment exceeds outstanding dues.');return false}m.dues+=a==='dues'?-amount:amount;if(a==='dues')DB.transactions.push({id:nextId(DB.transactions),title:m.name+' · dues',amount,date:TODAY,type:'income',category:'Dues',method:'Bank transfer',status:'posted'});save('Dues updated');$('#drawer').close()})}else if(a==='dues-all')openForm('Assign chapter dues',field('Amount per member','amount',120,'number',true),f=>{DB.members.filter(m=>!m.archived).forEach(m=>m.dues+=Number(f.get('amount')));save('Chapter dues assigned')});
else if(a==='reimb-approve'||a==='reimb-reject'){const r=DB.reimbursements.find(x=>x.id===n);r.status=a==='reimb-approve'?'approved':'rejected';if(r.status==='approved')DB.transactions.push({id:nextId(DB.transactions),title:r.title,amount:r.amount,date:TODAY,type:'expense',category:r.category,method:'Reimbursement',status:'posted'});save('Reimbursement '+r.status)}else if(a==='tx-paid'){DB.transactions.find(x=>x.id===n).status='posted';save('Transaction posted')}
else if(a==='budget'){const b=DB.budgets.find(x=>x.id===n);openForm('Edit budget',field('Category','name',b.name)+field('Budget','amount',b.amount,'number',true),f=>{Object.assign(b,{name:f.get('name'),amount:Number(f.get('amount'))});save('Budget updated')})}
else if(a==='wrap'){const r=DB.events.find(x=>x.id===n);openForm('Wrap up '+r.title,field('Revenue','revenue',r.revenue||0,'number')+field('Cost','cost',r.cost||0,'number')+field('Guests','guests',r.guests||0,'number')+field('What worked?','description',r.description,'textarea'),f=>{for(const k of ['revenue','cost','guests'])r[k]=Number(f.get(k));r.description=f.get('description');r.stage='done';save('Party wrap-up saved');$('#drawer').close()})}
else if(a==='service-hours'||a==='roll'||a==='attendance'){const ev=DB.events.find(x=>x.id===n);const roll=a==='roll'||a==='attendance';openForm(roll?'Chapter roll call':'Log service hours',liveMembers().map(m=>roll?checkField(m.name,'member-'+m.id,(ev.present||[]).includes(m.id)):field(m.name,'member-'+m.id,ev.hours?.[m.id]||0,'number')).join(''),f=>{if(roll){ev.present=liveMembers().filter(m=>f.has('member-'+m.id)).map(m=>m.id);const meetings=DB.events.filter(x=>x.category==='chapter'&&x.date<=TODAY);liveMembers().forEach(m=>m.attendance=Math.round(100*meetings.filter(x=>(x.present||[]).includes(m.id)).length/Math.max(1,meetings.length)))}else{ev.hours||={};liveMembers().forEach(m=>{const val=Number(f.get('member-'+m.id));m.hours+=val-(ev.hours[m.id]||0);ev.hours[m.id]=val})}save(roll?'Attendance saved':'Service hours saved');$('#drawer').close()})}
else if(a==='edit-member'){const m=DB.members.find(x=>x.id===n);openForm('Edit member',field('Name','name',m.name,'text',true)+field('Role','role',m.role,'text',false,DB.roles.map(r=>r.name||r.label))+field('GPA','gpa',m.gpa,'number'),f=>{const gpa=Number(f.get('gpa'));if(gpa>4){toast('Enter a GPA between 0 and 4.');return false}Object.assign(m,{name:f.get('name'),role:f.get('role'),gpa});save('Member updated');detail('member',n)})}
else if(a==='prep-add'){openForm('Add preparation item',field('Checklist item','label','','text',true),f=>{(DB.events.find(x=>x.id===n).prep??=[]).push({label:f.get('label'),done:false});save('Checklist item added');detail('event',n)})}
else if(a==='new-folder'||a==='new'&&id==='folder')openForm('New folder',field('Folder name','name','','text',true),f=>{DB.folders.push(f.get('name'));save('Folder created')});
else if(a==='org')openForm('Chapter identity',field('Chapter name','name',DB.org.name,'text',true)+field('Monogram','initials',DB.org.initials,'text',true),f=>{Object.assign(DB.org,Object.fromEntries(f));save('Chapter identity updated')});else if(a==='profile')detail('member',1);else if(a==='announcement')openForm('Chapter announcement',field('Announcement','text',DB.announcement,'textarea',true),f=>{DB.announcement=f.get('text');save('Announcement updated')});
else if(a==='vocabulary')openForm('Chapter vocabulary',Object.entries(DB.settings.vocabulary).map(([k,v])=>field(k,k,v,'text',true)).join(''),f=>{DB.settings.vocabulary=Object.fromEntries(f);save('Vocabulary updated')});else if(a==='thresholds')openForm('Standing thresholds',Object.entries(DB.settings.thresholds).map(([k,v])=>field(settingTitle(k),k,v,'number',true)).join(''),f=>{for(const [k,v]of f)DB.settings.thresholds[k]=Number(v);save('Standing thresholds updated')});
else if(a==='setting-add'||a==='setting-edit'){const [key,sid]=id.split(':'),list=key==='roles'?DB.roles:DB.settings[key],r=list.find(x=>x.id===Number(sid))||{};const fields=Object.keys(r).filter(k=>!['id','active','permissions'].includes(k));if(!fields.length)fields.push(key==='terms'?'name':'label',key==='metrics'?'target':key==='roles'?'rank':'type');openForm(settingTitle(key),fields.map(k=>field(settingTitle(k),k,r[k]||'',typeof r[k]==='number'||['rank','target'].includes(k)?'number':'text',true)).join('')+(key==='roles'?['Members','Meetings','Treasury','Events','Settings'].map(p=>checkField(p,'perm-'+p,r.permissions?.includes(p))).join(''):''),f=>{const vals=Object.fromEntries(f);if(key==='roles'){vals.permissions=['Members','Meetings','Treasury','Events','Settings'].filter(p=>f.has('perm-'+p));vals.name=vals.name||vals.label;for(const k of Object.keys(vals))if(k.startsWith('perm-'))delete vals[k]}if(r.id)Object.assign(r,vals);else list.push({id:nextId(list),...vals});save('Settings saved')})}
else if(a==='ask')ask();else if(a==='ask-question')ask(id);else if(a==='ask-propose'){proposal={title:'Check in on chapter follow-ups',date:'2026-09-11',owner:'Marcus Reyes',status:'open',description:'Review standing, outstanding dues, and overdue tasks.'};$('#ask-body').insertAdjacentHTML('beforeend',`<div class="ask-answer"><h3>Proposed task</h3><p>${proposal.title}<br>Marcus Reyes · Sep 11</p>${btn('Create this task','ask-approve','','primary')}</div>`)}else if(a==='ask-approve'&&proposal){DB.tasks.push({id:nextId(DB.tasks),...proposal});proposal=null;save('Follow-up task created');ask('What’s coming up?')}
else if(a==='health'||a==='my-hours'||a==='summarize'){const text=a==='health'?`${liveMembers().filter(m=>memberStatus(m)==='At Risk').length} members need a check-in. Attendance averages ${Math.round(average(liveMembers(),'attendance'))}%.`:a==='my-hours'?`Marcus has ${DB.members[0].hours} service hours this semester.`:(DB.events.find(x=>x.id===n)?.notes||'Add meeting notes to create a summary.');modal(a==='summarize'?'Meeting notes · local summary':'Chapter snapshot',`<div class="modal-content"><p class="detail-lines">${esc(text)}</p>${link('View relevant records',a==='my-hours'?'service':'brothers')}</div>`)}
else if(a==='timeline-glance'){U.filter=id==='required'?'Required':id==='deadlines'?'Deadlines':id==='overdue'?'Overdue':id==='week'?'This week':'All';render()}
else if(a==='export-members'||a==='export'&&id==='members')csv('chapter-roster',['Name','Role','Attendance','GPA','Service hours','Dues'],liveMembers().map(m=>[m.name,m.role,m.attendance,m.gpa,m.hours,m.dues]));else if(a==='export-transactions'||a==='export-report'||a==='export'&&['transactions','report'].includes(id))csv('chapter-finances',['Date','Title','Type','Category','Amount','Status'],DB.transactions.map(t=>[t.date,t.title,t.type,t.category,t.amount,t.status]));
else if(a==='quick')modal('Quick actions',`<div class="modal-content actions">${btn('Add task','new','task')}${btn('Plan event','new','event')}${btn('Invite people','invite')}${btn('Add document','new','doc')}</div>`);else if(a==='legend')modal('Timeline legend',`<div class="modal-content stack">${Object.values(cats).map(([label,color])=>pill(label,color)).join('')}<p>Required events carry an attendance badge. Deadlines come from your chapter tasks.</p></div>`);else if(a==='clear-search'){U.query='';U.filter='All';render()}else if(a==='billing-manage'||a==='billing-details'||a==='invoice')modal(a==='invoice'?id+' invoice':'Billing preview',`<div class="modal-content"><h3>Standard · $25 / month</h3><p>Lambda Sigma Phi · ${liveMembers().length} members</p><p>Visa •••• 4242 · Paid</p><p class="muted">This is a mock billing surface. Subscription and payment details are fictional.</p></div>`);
});
document.addEventListener('submit',e=>{if(e.target.id==='generic-form'){e.preventDefault();const result=formHandler?.(new FormData(e.target));if(result!==false)$('#modal').close()}if(e.target.id==='ask-form'){e.preventDefault();ask(new FormData(e.target).get('question'));e.target.reset()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;U.query=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.change){const k=el.dataset.change;if(k==='show-done')U.showDone=el.checked;else if(k==='doc-sort')U.sort=el.value;else U[k]=el.value;render()}if(el.dataset.notes){DB.events.find(x=>x.id===Number(el.dataset.notes)).notes=el.value;localStorage.setItem(KEY,JSON.stringify(DB));toast('Notes saved')}if(el.dataset.workflow){DB.settings.workflows[el.dataset.workflow]=el.checked;save('Workspace updated')}if(el.dataset.prep){const [id,i]=el.dataset.prep.split(':').map(Number);const ev=DB.events.find(x=>x.id===id);if(typeof ev.prep[i]==='string')ev.prep[i]={label:ev.prep[i],done:false};ev.prep[i].done=el.checked;save('Checklist updated')}});
$('#nav-shade').onclick=()=>{$('#sidebar').classList.remove('open');$('#sidebar').inert=innerWidth<1024;$('#nav-shade').hidden=true};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();ask()}});window.addEventListener('hashchange',navigate);window.addEventListener('resize',()=>{$('#sidebar').inert=innerWidth<1024&&!$('#sidebar').classList.contains('open')});navigate();
