const settingMeta={
 general:['Chapter profile','Chapter identity, monogram and general preferences.','Settings'],
 vocabulary:['Language & labels','Choose the words your chapter uses for members, meetings and periods.','Docs'],
 accounts:['Member accounts','Review the members connected to your chapter.','Brotherhood'],
 invitations:['Invitations','Create and manage invite links. New members join after officer approval.','Docs'],
 roles:['Roles & permissions','Define officer responsibilities and who can access each area.','Brotherhood'],
 'member-fields':['Member fields','Customize roster information, such as graduation year or major.','Brotherhood'],
 thresholds:['Good standing','Set attendance, GPA and service-hour requirements.','flag'],
 semesters:['Semesters','Manage reporting periods and review the current semester.','Timeline'],
 'custom-metrics':['Custom metrics','Track additional member goals, such as recruitment points.','Chapter'],
 'event-types':['Event types','Organize the timeline with event categories and colors.','Timeline'],
 'event-fields':['Event fields','Choose the extra information collected for events.','Programming'],
 'money-categories':['Money categories','Organize treasury income and expenses for reporting.','Treasury'],
 workflows:['Workspace & workflows','Choose which tools appear in your chapter navigation.','Settings'],
 'activity-log':['Activity log','See what changed across your chapter and when.','clock'],
 billing:['Plan & billing','Manage your app subscription, payment details and invoices.','Treasury']
};
const settingHref=s=>s==='billing'?'#/billing':'#/settings/'+s;
const overviewGroups=[
 ['Your chapter','The basics that make this workspace yours.','lilac',['general','vocabulary','workflows']],
 ['People & access','Who belongs here, and what they can do.','mint',['invitations','accounts','roles','member-fields']],
 ['Standards & reporting','Define a successful semester.','butter',['thresholds','semesters','custom-metrics']],
 ['Events & finance','Set up how your chapter runs.','sky',['event-types','event-fields','money-categories']],
 ['Administration','Your subscription and chapter history.','peach',['billing','activity-log']]
];
function settingsSummary(s){const keys={'member-fields':'memberFields','event-fields':'eventFields','event-types':'eventTypes','money-categories':'moneyCategories','custom-metrics':'metrics'};if(keys[s])return DB.settings[keys[s]].length+' configured';if(s==='semesters')return DB.org.term;if(s==='accounts')return liveMembers().length+' members';if(s==='roles')return DB.roles.length+' roles';if(s==='invitations')return DB.invitations.filter(i=>i.active).length+' active invite'+(DB.invitations.filter(i=>i.active).length===1?'':'s');if(s==='billing')return 'Standard plan';if(s==='thresholds')return DB.settings.thresholds.attendance+'% attendance';return '';}
function settingsOverview(){return `<div class="settings-home">${header('WORKSPACE / SETTINGS','A home for every setting.','Manage your chapter, your people and the way you work.',pill('Org admin','lilac'))}
<div class="settings-context"><span class="settings-monogram">${esc(DB.org.initials)}</span><div><b>${esc(DB.org.name)}</b><p>${esc(DB.org.term)} <span>·</span> ${liveMembers().length} active members</p></div><a href="#/settings/general">Chapter profile ${icon('chevron')}</a></div>
<div class="settings-find"><label for="settings-search">Find a setting</label><div>${icon('search')}<input type="search" id="settings-search" placeholder="Try “permissions”, “attendance” or “invoices”…" autocomplete="off"><button type="button" id="settings-clear" hidden>Clear</button></div></div>
<section class="settings-quick" aria-label="Common actions"><span class="eyebrow">QUICK ACCESS</span><a href="#/settings/invitations">${icon('Docs')} Invite members ${icon('chevron')}</a><a href="#/settings/semesters">${icon('Timeline')} Manage semester ${icon('chevron')}</a><a href="#/settings/roles">${icon('Brotherhood')} Edit permissions ${icon('chevron')}</a></section>
${DB.joins.length?`<a class="settings-pending" href="#/brothers"><span class="settings-count">${DB.joins.length}</span><span><b>People are waiting to join</b><small>Review their requests before they appear on your roster.</small></span><strong>Review requests ${icon('chevron')}</strong></a>`:''}
<p id="settings-results" class="settings-result-count" role="status" aria-live="polite">All 15 settings</p>
<div class="settings-directory">${overviewGroups.map(([name,desc,tone,items],i)=>`<section class="settings-category" style="${tint(tone)}"><header><span class="settings-group-number">0${i+1}</span><div><h2>${name}</h2><p>${desc}</p></div></header><div>${items.map(s=>`<a class="settings-entry" href="${settingHref(s)}" data-setting-search="${esc([name,s,...settingMeta[s]].join(' ').toLowerCase())}"><span class="settings-entry-icon">${icon(settingMeta[s][2])}</span><span class="settings-entry-copy"><b>${settingMeta[s][0]}</b><small>${settingMeta[s][1]}</small>${settingsSummary(s)?`<em>${esc(settingsSummary(s))}</em>`:''}</span>${icon('chevron')}</a>`).join('')}</div></section>`).join('')}</div>
<div id="settings-empty" class="settings-empty" hidden><h2>No settings found</h2><p>Try a broader word, like “members”, “events” or “billing”.</p></div>
<aside class="settings-data"><div><b>Your chapter’s data</b><p>Download a copy of the sample roster or financial records.</p></div><div class="actions">${btn('Export roster','export-members')}${btn('Export finances','export-transactions')}</div></aside>
<p class="settings-local-note">Interactive mock · Changes are saved in this browser only.</p></div>`;}
document.addEventListener('input',e=>{if(e.target.id==='settings-search')filterSettings(e.target.value)});
document.addEventListener('click',e=>{if(e.target.closest('#settings-clear')){document.getElementById('settings-search').value='';filterSettings('');document.getElementById('settings-search').focus()}});
function filterSettings(value){const terms=value.toLowerCase().trim().split(/\s+/).filter(Boolean);let count=0;document.querySelectorAll('[data-setting-search]').forEach(el=>{el.hidden=!terms.every(t=>el.dataset.settingSearch.includes(t));if(!el.hidden)count++});document.querySelectorAll('.settings-category').forEach(el=>el.hidden=![...el.querySelectorAll('[data-setting-search]')].some(a=>!a.hidden));document.getElementById('settings-results').textContent=terms.length?`${count} setting${count===1?'':'s'} found`:'All 15 settings';document.getElementById('settings-empty').hidden=count>0;document.getElementById('settings-clear').hidden=!value;}
const settingGroups=Object.fromEntries(overviewGroups.map(([name,description,tone,items])=>[name,items]));
const settingTitle=s=>s.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
function settingsPage(){const s=U.setting;if(s==='index')return settingsOverview();let body='';if(s==='index')body=Object.entries(settingGroups).map(([g,items])=>card(g,items.map(x=>`<a class="row" href="#/${x==='billing'?'billing':'settings/'+x}"><div><b>${settingTitle(x)}</b><p class="muted">Manage your chapter’s ${settingTitle(x).toLowerCase()}.</p></div><span>↗</span></a>`).join(''),'lilac','Settings')).join('');else if(s==='general')body=card('Chapter identity',`<h2>${esc(DB.org.name)}</h2><p>${esc(DB.org.term)} · ${liveMembers().length} active members</p>${btn('Edit identity','org')}`);else if(s==='vocabulary')body=card('Make it sound like your chapter',Object.entries(DB.settings.vocabulary).map(([k,v])=>`<div class="row"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')+btn('Edit vocabulary','vocabulary'));else if(s==='thresholds')body=card('Good standing',Object.entries(DB.settings.thresholds).map(([k,v])=>`<div class="row"><span>${settingTitle(k)}</span><b>${v}${k==='attendance'?'%':''}</b></div>`).join('')+btn('Edit thresholds','thresholds'));else if(s==='accounts')body=card('Connected members',rosterTable(liveMembers(),true));else if(s==='invitations')body=card('Invite links',DB.invitations.map(i=>`<div class="row"><div><b>${esc(i.title||i.label||i.name)}</b><p>${i.uses} requests · ${esc(i.role)}</p></div>${pill(i.active?'Active':'Disabled',i.active?'mint':'rose')}${btn(i.active?'Disable':'Enable','invite-toggle',i.id,'small')}</div>`).join('')+btn('Create invite','invite'));else if(s==='roles')body=card('Roles & permissions',DB.roles.map(r=>`<div class="row"><div><b>${esc(r.name||r.label)}</b><p>${r.permissions.join(' · ')||'Member access'}</p></div>${btn('Edit','setting-edit',`roles:${r.id}`,'small')}</div>`).join('')+btn('New role','setting-add','roles'));else if(s==='workflows')body=card('Choose your workspace',Object.entries(DB.settings.workflows).map(([k,v])=>`<label class="toggle-row"><div><b>${navName(k)}</b><p class="muted">Show this workflow in your navigation.</p></div><input type="checkbox" data-workflow="${k}" ${v?'checked':''}></label>`).join(''));else if(s==='activity-log')body=card('Chapter activity',activityRows(DB.activity));else {const key={'member-fields':'memberFields','event-fields':'eventFields','custom-metrics':'metrics','event-types':'eventTypes','money-categories':'moneyCategories',semesters:'terms'}[s];if(key)body=card(settingTitle(s),(DB.settings[key]||[]).map(x=>`<div class="row"><div><b>${esc(x.label||x.name)}</b><p class="muted">${esc(x.type||x.start||'')}${x.target?' · Target '+x.target:''}</p></div>${x.active?pill('Current','mint'):''}${btn('Edit','setting-edit',`${key}:${x.id}`,'small')}</div>`).join('')+btn('Add '+settingTitle(s).replace(/s$/,''),'setting-add',key));}
return `<div class="settings-detail">${link('← All settings','settings','settings-back')}${header('CHAPTER SETTINGS',settingMeta[s]?.[0]||settingTitle(s),settingMeta[s]?.[1]||'Manage your chapter preferences.')}<label class="settings-mobile-picker">Settings section<select id="settings-section-picker">${Object.entries(settingMeta).map(([id,m])=>`<option value="${settingHref(id)}" ${s===id?'selected':''}>${m[0]}</option>`).join('')}</select></label><div class="settings-grid"><nav class="settings-nav" aria-label="Settings sections">${Object.entries(settingGroups).map(([g,items])=>`<p class="eyebrow">${g}</p>${items.map(x=>`<a class="setting-link ${s===x?'on':''}" ${s===x?'aria-current="page"':''} href="${settingHref(x)}">${settingMeta[x]?.[0]||settingTitle(x)}</a>`).join('')}`).join('')}</nav><div class="stack"><div class="settings-scope">${icon('Settings')} Changes here apply to ${esc(DB.org.name)}.</div>${s==='invitations'?`<aside class="settings-notice"><b>Every new member needs approval.</b><p>Invite links let people request to join. Review requests in Brotherhood before anyone is added to your roster.</p>${link('Review join requests'+(DB.joins.length?' · '+DB.joins.length:''),'brothers')}</aside>`:''}${body}</div></div></div>`}

function billingPage(){return header('A LITTLE HOUSEKEEPING','Your plan','Everything your chapter needs, with room to grow.',link('← Settings','settings'))+`<div class="grid equal billing-grid">${card('Standard',`<span class="eyebrow">5–50 MEMBERS</span><div class="plan-price">$25 <small>/ month</small></div><p>One workspace. Every workflow. A calmer chapter.</p>${pill('Active · Sample subscription','mint')}<div class="row"><span>Members</span><b>${liveMembers().length} / 50</b></div><div class="row"><span>Next renewal</span><b>October 1, 2026</b></div>${btn('Manage subscription','billing-manage','','primary')}`,'mint','Treasury')}${card('Payment & invoices',`<div class="row"><span>Visa ending in 4242</span>${pill('Sample','butter')}</div><p class="muted">Billing contact · nadia@example.com</p>${btn('Update billing details','billing-details')}<div class="row"><span>September 2026</span><b>$25.00</b>${btn('View invoice','invoice','September','small')}</div><div class="row"><span>August 2026</span><b>$25.00</b>${btn('View invoice','invoice','August','small')}</div>`,'butter','Docs')}</div>`}

document.addEventListener('change',e=>{if(e.target.id==='settings-section-picker')location.hash=e.target.value});
